// auto-generated by: bella secrets generate typescript
// project: anahuarket/develop
// generated: 2026-05-22 08:07:36 UTC
// DO NOT edit manually — re-run bella secrets generate typescript to update.

function requireEnv(key: string): string {
  const v = process.env[key];
  if (v === undefined) throw new Error(`Required env var '${key}' is not set.`);
  return v;
}

export const anahuarketsecrets = {
  get authSecret(): string { return requireEnv("AUTH_SECRET"); },
  get authUrl(): string { return requireEnv("AUTH_URL");},
  get cloudinaryApiKey(): number { return parseInt(requireEnv("CLOUDINARY_API_KEY"), 10); },
  get cloudinaryApiSecret(): string { return requireEnv("CLOUDINARY_API_SECRET"); },
  get databaseUrl(): string { return requireEnv("DATABASE_URL"); },
  get dbHost(): string { return requireEnv("DB_HOST"); },
  get dbName(): string { return requireEnv("DB_NAME"); },
  get dbPassword(): Buffer { return Buffer.from(requireEnv("DB_PASSWORD"), "base64"); },
  get dbPort(): number { return parseInt(requireEnv("DB_PORT"), 10); },
  get dbUser(): string { return requireEnv("DB_USER"); },
  get dokployWebhookUrl(): string { return requireEnv("DOKPLOY_WEBHOOK_URL"); },
  get nextPublicCloudinaryCloudName(): string { return requireEnv("NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME"); },
  get nextauthUrl(): string { return requireEnv("NEXTAUTH_URL");},
  get resendApiKey(): string { return requireEnv("RESEND_API_KEY"); },
  get sentryAuthToken(): string { return requireEnv("SENTRY_AUTH_TOKEN"); },
} as const;
