name: CI/CD Pipeline a VPS

on:
  push:
    branches: [ "develop" ] # Se ejecuta al hacer push a la rama develop

env:
  IMAGE_NAME: anahuarket
  IMAGE_TAG: develop
  CONTAINER_NAME: anahuarket-develop
  BELLA_BAXTER_URL: https://console.bella-baxter.io/projects/anahuarket/environments/develop

jobs:
  build-and-deploy:
    environment: develop
    runs-on: ubuntu-latest
    env:
      SENTRY_ENVIRONMENT: develop
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    
    - name: Login en GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Bella Baxter
      uses: cosmic-chimps/bella-baxter-setup-action@v0.1.1-preview.88
      with:
        bella-url: ${{ env.BELLA_BAXTER_URL }}

    - run: bella login --api-key ${{ secrets.BELLA_BAXTER_API_KEY }}

    - run: bella run -p my-api -e production -- ./deploy.sh
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Asegúrate de que el nombre del owner (tu usuario) esté en minúsculas
        tags: ghcr.io/garciafah/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        build-args: |
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ENVIRONMENT=develop
      
    # Notifica a dokploy para que deploye la nueva imagen
    - name: Notificar a Dokploy (Trigger Deploy)
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.DOKPLOY_WEBHOOK_URL }})
        if [ "$response" -ne 200 ]; then
          echo "Error al notificar con Dokploy"
          exit 1
        fi
          echo "Dokploy notificado con éxito. Despliegue en curso."